export const ACTION_SAVE_PHONENUMBER = 'ACTION_SAVE_PHONENUMBER'

export const ACTION_SAVE_PROFILE = 'ACTION_SAVE_PROFILE'

export const ACTION_SAVE_USER_ID = 'ACTION_SAVE_USER_ID'

// Collection
export const CHANGE_COLLECTION_NAME = 'CHANGE_COLLECTION_NAME'
export const CHANGE_COLLECTION_VISIBILITY = 'CHANGE_COLLECTION_VISIBILITY'
export const RESET_COLLECTION_FIELD = 'RESET_COLLECTION_FIELD'